version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: iss_tracker
      POSTGRES_USER: iss_user
      POSTGRES_PASSWORD: iss_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

  iss-tracker-app:
    # Build the image from the Dockerfile in the current directory
    build: .
    ports:
      # Map the host's port 8081 to the container's port 8081
      - "8081:8081"
    environment:
      # Override application.properties to connect to other containers
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/iss_tracker
      - SPRING_DATA_REDIS_HOST=redis
    # Ensure the database and redis are running before starting the app
    depends_on:
      - postgres
      - redis
    restart: always

volumes:
  postgres-data:
  redis-data: